---
title: "HMS PGP Microbiome data"
author: "Philip Chase"
date: "4/8/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r get_public_genetic_data}

library(tidyr)
library(tibble)
library(jsonlite)

# Download data file
microbiome = '/Users/pbchase/classes/gms6804-group3-project/microbiome'
setwd(microbiome)
dataURL <- "https://my.pgp-hms.org/public_genetic_data.json"
dataFile <- "public_genetic_data.json"

if (!file.exists(dataFile)){
    print("Downloading data file")
    download.file(dataURL, dataFile, "curl", quiet=TRUE)
}

json_data <- fromJSON(readLines(dataFile))
genomic_data <- json_data[["aaData"]]

microbiome_in_values <- genomic_data %>% filter(grepl("Microbiome",data_type) | grepl("Microbiome",download_url) | grepl("Microbiome",name) | grepl("Microbiome",description))  %>% mutate(clean_name = tolower(gsub("#","", gsub('"', '', gsub(" ", "_", name)))))

count(microbiome_in_values, download_url) %>% arrange(desc(n)) %>% mutate(Percent = round(n / sum(n),3))
summary(microbiome_in_values %>% filter(is.na(download_url)))

microbiome_with_download_url <- microbiome_in_values %>% filter(!is.na(download_url)) %>% select(name,data_type) 

combine_names <- function(x) {
  x <- gsub("^(Microbiome report for PGP kit).*", "\\1", x, ignore.case=TRUE)
  x <- gsub("^(Microbiome .American Gut.).*", "\\1", x, ignore.case=TRUE)
  x <- gsub("Microbiome data for PGP kit.*(fna.gz).*", "Microbiome data for PGP kit - fna.gz", x, ignore.case=TRUE)
  x <- gsub("Microbiome data for PGP kit.*(txt).*", "Microbiome data for PGP kit - txt", x, ignore.case=TRUE)
  x <- gsub("^(American Gut).*", "\\1", x, ignore.case=TRUE)
  x <- gsub("^(uBiome).*", "uBiome", x, ignore.case=TRUE)
}

microbiome_with_download_url$file_type <- combine_names(microbiome_with_download_url$name)
count(microbiome_with_download_url, file_type) %>% arrange(desc(n)) %>% mutate(Percent = round(n / sum(n),3))
```

